"""Populate the database with sample data for demonstration."""

from datetime import date, time, timedelta

from app import create_app
from extensions import db
from models import (
    Client, Contact, FollowUp, QuickFunction, DEFAULT_QUICK_FUNCTIONS,
    InteractionType, DEFAULT_INTERACTION_TYPES,
    CustomFieldDefinition, CustomFieldValue, DEFAULT_CUSTOM_FIELDS,
    AttachmentCategory, DEFAULT_ATTACHMENT_CATEGORIES,
    AttachmentTag, DEFAULT_ATTACHMENT_TAGS,
    Attachment,
    User,
)


def seed():
    app = create_app()
    with app.app_context():
        # Clear existing data
        db.session.execute(db.text("DELETE FROM attachment_tag_map"))
        Attachment.query.delete()
        AttachmentTag.query.delete()
        AttachmentCategory.query.delete()
        CustomFieldValue.query.delete()
        CustomFieldDefinition.query.delete()
        FollowUp.query.delete()
        Contact.query.delete()
        Client.query.delete()
        QuickFunction.query.delete()
        InteractionType.query.delete()
        User.query.delete()
        db.session.commit()

        # --- Users ---
        users = []
        for udata in [
            {"username": "admin", "display_name": "Administrator", "role": "admin", "pw": "admin123"},
            {"username": "manager1", "display_name": "Sarah Manager", "role": "manager", "pw": "manager123"},
            {"username": "user1", "display_name": "James User", "role": "user", "pw": "user123"},
            {"username": "user2", "display_name": "Emily User", "role": "user", "pw": "user123"},
        ]:
            u = User(username=udata["username"], display_name=udata["display_name"], role=udata["role"])
            u.set_password(udata["pw"])
            db.session.add(u)
            users.append(u)
        db.session.flush()

        # Ownership mapping: clients 0-4 → admin, 5-9 → manager1, 10-12 → user1, 13-14 → user2
        owner_map = (
            [users[0]] * 5 + [users[1]] * 5 + [users[2]] * 3 + [users[3]] * 2
        )

        # --- Interaction Types ---
        for i, it_data in enumerate(DEFAULT_INTERACTION_TYPES):
            db.session.add(InteractionType(sort_order=i, **it_data))
        db.session.flush()

        # --- Attachment Categories ---
        attachment_cats = []
        for i, ac_data in enumerate(DEFAULT_ATTACHMENT_CATEGORIES):
            ac = AttachmentCategory(sort_order=i, **ac_data)
            db.session.add(ac)
            attachment_cats.append(ac)
        db.session.flush()

        # --- Attachment Tags ---
        attachment_tags = []
        for i, at_data in enumerate(DEFAULT_ATTACHMENT_TAGS):
            at = AttachmentTag(sort_order=i, **at_data)
            db.session.add(at)
            attachment_tags.append(at)
        db.session.flush()

        # --- Custom Field Definitions ---
        custom_field_defs = []
        for i, cf_data in enumerate(DEFAULT_CUSTOM_FIELDS):
            cf = CustomFieldDefinition(sort_order=i, **cf_data)
            db.session.add(cf)
            custom_field_defs.append(cf)
        db.session.flush()

        # --- Quick Functions ---
        for i, qf_data in enumerate(DEFAULT_QUICK_FUNCTIONS):
            db.session.add(QuickFunction(sort_order=i, **qf_data))
        db.session.flush()

        # --- Clients (15 total) ---
        clients = [
            # 0 – Thornbury & Associates
            Client(
                company_name="Thornbury & Associates",
                industry="Legal Services",
                phone="020 7946 0123",
                email="info@thornbury.co.uk",
                contact_person="Margaret Thornbury",
                status="active",
            ),
            # 1 – Brightwell Manufacturing
            Client(
                company_name="Brightwell Manufacturing",
                industry="Manufacturing",
                phone="0121 496 0456",
                email="sales@brightwell.co.uk",
                contact_person="David Brightwell",
                status="active",
            ),
            # 2 – Hargreaves Digital
            Client(
                company_name="Hargreaves Digital",
                industry="Technology",
                phone="0161 946 0789",
                email="hello@hargreaves.digital",
                contact_person="Sarah Hargreaves",
                status="active",
            ),
            # 3 – Pemberton Logistics
            Client(
                company_name="Pemberton Logistics",
                industry="Transport & Logistics",
                phone="0113 496 0321",
                email="enquiries@pemberton-logistics.co.uk",
                contact_person="James Pemberton",
                status="prospect",
            ),
            # 4 – Ashworth Catering
            Client(
                company_name="Ashworth Catering",
                industry="Hospitality",
                phone="0151 946 0654",
                email="bookings@ashworthcatering.co.uk",
                contact_person="Emily Ashworth",
                status="prospect",
            ),
            # 5 – Cartwright Properties
            Client(
                company_name="Cartwright Properties",
                industry="Real Estate",
                phone="020 7946 0987",
                email="lettings@cartwrightprops.co.uk",
                contact_person="Richard Cartwright",
                status="lead",
            ),
            # 6 – Fenwick & Cole Accountants
            Client(
                company_name="Fenwick & Cole Accountants",
                industry="Financial Services",
                phone="0117 496 0147",
                email="partners@fenwickcole.co.uk",
                contact_person="Helen Fenwick",
                status="lead",
            ),
            # 7 – Greenfield Organics
            Client(
                company_name="Greenfield Organics",
                industry="Agriculture",
                phone="0115 496 0258",
                email="farm@greenfieldorganics.co.uk",
                contact_person="Tom Greenfield",
                status="active",
            ),
            # 8 – Mercer Engineering
            Client(
                company_name="Mercer Engineering",
                industry="Engineering",
                phone="0114 496 0369",
                email="projects@mercer-eng.co.uk",
                contact_person="Alan Mercer",
                status="inactive",
            ),
            # 9 – Whitmore Creative Agency
            Client(
                company_name="Whitmore Creative Agency",
                industry="Marketing",
                phone="020 7946 0741",
                email="studio@whitmorecreative.co.uk",
                contact_person="Lucy Whitmore",
                status="lead",
            ),
            # 10 – Oakbridge Consulting
            Client(
                company_name="Oakbridge Consulting",
                industry="Management Consulting",
                phone="020 7946 0852",
                email="enquiries@oakbridgeconsulting.co.uk",
                contact_person="William Oakbridge",
                status="active",
            ),
            # 11 – Redcastle Healthcare
            Client(
                company_name="Redcastle Healthcare",
                industry="Healthcare",
                phone="0161 946 0963",
                email="admin@redcastlehealthcare.co.uk",
                contact_person="Priya Sharma",
                status="active",
            ),
            # 12 – Longmere Education
            Client(
                company_name="Longmere Education",
                industry="Education",
                phone="0113 496 0174",
                email="info@longmere-education.co.uk",
                contact_person="Catherine Longmere",
                status="prospect",
            ),
            # 13 – Stonewick Retail Group
            Client(
                company_name="Stonewick Retail Group",
                industry="Retail",
                phone="0151 946 0285",
                email="buyers@stonewickretail.co.uk",
                contact_person="Daniel Stonewick",
                status="lead",
            ),
            # 14 – Blackwood Energy Solutions
            Client(
                company_name="Blackwood Energy Solutions",
                industry="Energy",
                phone="0131 496 0396",
                email="projects@blackwoodenergy.co.uk",
                contact_person="Fiona Blackwood",
                status="inactive",
            ),
        ]
        # Assign ownership to clients
        for i, client in enumerate(clients):
            client.user_id = owner_map[i].id

        db.session.add_all(clients)
        db.session.flush()

        # Helper: get owner for a client by index
        def _owner_id(client_idx):
            return owner_map[client_idx].id

        today = date.today()

        # --- Contacts (interaction history) — full year Apr 2025 – Mar 2026 ---
        contacts = [
            # ── April 2025 — cold outreach & early prospecting ──
            Contact(client_id=clients[0].id, date=date(2025, 4, 2),
                    contact_type="email",
                    notes="Cold email introducing our consultancy services to Margaret.",
                    outcome="No reply — will follow up in two weeks"),
            Contact(client_id=clients[1].id, date=date(2025, 4, 7),
                    time=time(9, 30),
                    contact_type="phone",
                    notes="Cold call to Brightwell reception about manufacturing support.",
                    outcome="Gatekeeper took message for David Brightwell"),
            Contact(client_id=clients[5].id, date=date(2025, 4, 10),
                    contact_type="email",
                    notes="Sent brochure about commercial property management services.",
                    outcome="Auto-reply — out of office"),
            Contact(client_id=clients[9].id, date=date(2025, 4, 14),
                    time=time(11, 0),
                    contact_type="phone",
                    notes="Exploratory call with Lucy about potential branding work.",
                    outcome="Interested but busy with current campaign — call back June"),
            Contact(client_id=clients[3].id, date=date(2025, 4, 18),
                    contact_type="email",
                    notes="Sent logistics consultancy overview to Pemberton.",
                    outcome="James replied asking for case studies"),
            Contact(client_id=clients[7].id, date=date(2025, 4, 22),
                    time=time(14, 0),
                    contact_type="phone",
                    notes="Initial enquiry about organic supply chain consulting.",
                    outcome="Tom interested — wants to discuss after harvest season"),
            Contact(client_id=clients[13].id, date=date(2025, 4, 25),
                    contact_type="email",
                    notes="Cold email to Stonewick Retail about inventory optimisation.",
                    outcome="No response"),
            Contact(client_id=clients[6].id, date=date(2025, 4, 28),
                    contact_type="email",
                    notes="Sent intro email about accounting software integration services.",
                    outcome="Helen replied — not a priority right now"),

            # ── May 2025 — follow-ups on April outreach ──
            Contact(client_id=clients[0].id, date=date(2025, 5, 5),
                    time=time(10, 0),
                    contact_type="phone",
                    notes="Follow-up call to Margaret on April email.",
                    outcome="Interested in learning more — send detailed proposal"),
            Contact(client_id=clients[3].id, date=date(2025, 5, 8),
                    contact_type="email",
                    notes="Sent three logistics case studies as requested.",
                    outcome="James forwarded to operations director"),
            Contact(client_id=clients[1].id, date=date(2025, 5, 12),
                    time=time(15, 0),
                    contact_type="phone",
                    notes="Second attempt — reached David Brightwell directly.",
                    outcome="Agreed to a site visit in June"),
            Contact(client_id=clients[14].id, date=date(2025, 5, 15),
                    contact_type="email",
                    notes="Cold email to Blackwood Energy about sustainability consulting.",
                    outcome="Fiona replied — keen to explore after Q2 close"),
            Contact(client_id=clients[4].id, date=date(2025, 5, 19),
                    time=time(11, 30),
                    contact_type="phone",
                    notes="Met Emily Ashworth at hospitality networking event.",
                    outcome="Exchanged details, will send catering partnership proposal"),
            Contact(client_id=clients[11].id, date=date(2025, 5, 22),
                    contact_type="email",
                    notes="Referral from NHS contact — sent introductory pack to Redcastle.",
                    outcome="Priya acknowledged receipt, will review in June"),
            Contact(client_id=clients[10].id, date=date(2025, 5, 28),
                    contact_type="email",
                    notes="Sent introductory email about management consulting services.",
                    outcome="William's PA replied — scheduling a call"),

            # ── June 2025 — first meetings, warming up pipeline ──
            Contact(client_id=clients[0].id, date=date(2025, 6, 3),
                    contact_type="email",
                    notes="Sent detailed proposal document for legal consultancy support.",
                    outcome="Margaret said she'll review over the weekend"),
            Contact(client_id=clients[1].id, date=date(2025, 6, 10),
                    time=time(10, 0),
                    contact_type="meeting",
                    notes="Factory site visit at Brightwell Works, Aston Road.",
                    outcome="Identified production line bottlenecks — drafting assessment"),
            Contact(client_id=clients[4].id, date=date(2025, 6, 12),
                    contact_type="email",
                    notes="Sent catering partnership proposal to Emily.",
                    outcome="Under review — needs sign-off from business partner"),
            Contact(client_id=clients[10].id, date=date(2025, 6, 16),
                    time=time(14, 30),
                    contact_type="phone",
                    notes="Introductory call with William Oakbridge.",
                    outcome="Very engaged — wants a face-to-face in autumn"),
            Contact(client_id=clients[12].id, date=date(2025, 6, 18),
                    contact_type="email",
                    notes="Cold email about education sector consulting to Longmere.",
                    outcome="Catherine interested — asked for more info"),
            Contact(client_id=clients[5].id, date=date(2025, 6, 20),
                    time=time(9, 0),
                    contact_type="phone",
                    notes="Follow-up on April brochure — Richard now available.",
                    outcome="Wants to discuss three specific commercial properties"),
            Contact(client_id=clients[8].id, date=date(2025, 6, 24),
                    contact_type="email",
                    notes="Sent introductory email about engineering project management.",
                    outcome="Alan replied — has a project starting in September"),
            Contact(client_id=clients[3].id, date=date(2025, 6, 27),
                    time=time(16, 0),
                    contact_type="phone",
                    notes="Call with Pemberton operations director about case studies.",
                    outcome="Positive — wants pricing for logistics audit"),

            # ── July 2025 — summer activity, some slowdown ──
            Contact(client_id=clients[0].id, date=date(2025, 7, 3),
                    time=time(11, 0),
                    contact_type="phone",
                    notes="Margaret reviewed proposal — has questions on scope.",
                    outcome="Scheduled face-to-face for October"),
            Contact(client_id=clients[0].id, date=date(2025, 7, 15),
                    contact_type="email",
                    notes="Sent revised scope document addressing Margaret's questions.",
                    outcome="Auto-reply — out of office until August"),
            Contact(client_id=clients[1].id, date=date(2025, 7, 8),
                    contact_type="email",
                    notes="Sent production line assessment report to David.",
                    outcome="David forwarded to technical director for review"),
            Contact(client_id=clients[3].id, date=date(2025, 7, 14),
                    contact_type="email",
                    notes="Sent logistics audit pricing proposal.",
                    outcome="James said he'll discuss with board after summer"),
            Contact(client_id=clients[12].id, date=date(2025, 7, 18),
                    time=time(10, 0),
                    contact_type="phone",
                    notes="Call with Catherine about education consulting needs.",
                    outcome="Wants to explore curriculum review project — call back September"),
            Contact(client_id=clients[7].id, date=date(2025, 7, 22),
                    contact_type="email",
                    notes="Follow-up email to Tom about supply chain consulting.",
                    outcome="Tom busy with harvest — revisit in October"),
            Contact(client_id=clients[14].id, date=date(2025, 7, 28),
                    time=time(15, 0),
                    contact_type="phone",
                    notes="Follow-up call with Fiona about energy consulting.",
                    outcome="Budget confirmed — wants a formal proposal in September"),

            # ── August 2025 — quieter month, maintaining contact ──
            Contact(client_id=clients[1].id, date=date(2025, 8, 5),
                    time=time(10, 0),
                    contact_type="phone",
                    notes="Chased technical director on assessment report feedback.",
                    outcome="Gatekeeper took message, promised callback"),
            Contact(client_id=clients[5].id, date=date(2025, 8, 11),
                    contact_type="email",
                    notes="Sent property portfolio with three commercial unit details.",
                    outcome="Richard reviewing — will respond after holiday"),
            Contact(client_id=clients[8].id, date=date(2025, 8, 18),
                    time=time(14, 0),
                    contact_type="phone",
                    notes="Call with Alan about September engineering project.",
                    outcome="Confirmed start date — wants site visit first"),
            Contact(client_id=clients[8].id, date=date(2025, 8, 22),
                    contact_type="email",
                    notes="Sent introductory pack about engineering project management.",
                    outcome="Replied with interest in autumn projects"),
            Contact(client_id=clients[9].id, date=date(2025, 8, 25),
                    time=time(11, 0),
                    contact_type="phone",
                    notes="Reconnected with Lucy about branding project.",
                    outcome="Campaign finished — ready to discuss in September"),
            Contact(client_id=clients[6].id, date=date(2025, 8, 28),
                    contact_type="email",
                    notes="Follow-up on accounting integration — new tax year approaching.",
                    outcome="Helen more receptive — asked for a meeting in October"),

            # ── September 2025 — autumn ramp-up ──
            Contact(client_id=clients[14].id, date=date(2025, 9, 2),
                    contact_type="email",
                    notes="Sent formal energy audit proposal to Fiona.",
                    outcome="Under internal review"),
            Contact(client_id=clients[9].id, date=date(2025, 9, 5),
                    time=time(10, 0),
                    contact_type="meeting",
                    notes="Creative brief meeting at Whitmore studio in Shoreditch.",
                    outcome="Agreed brand refresh scope — awaiting budget approval"),
            Contact(client_id=clients[8].id, date=date(2025, 9, 8),
                    time=time(9, 0),
                    contact_type="meeting",
                    notes="Site visit at Mercer Engineering works in Sheffield.",
                    outcome="Identified inefficiencies in project handover process"),
            Contact(client_id=clients[14].id, date=date(2025, 9, 10),
                    time=time(14, 30),
                    contact_type="phone",
                    notes="Chased Fiona on energy audit proposal status.",
                    outcome="Asked to send overview brochure to CEO"),
            Contact(client_id=clients[12].id, date=date(2025, 9, 15),
                    contact_type="email",
                    notes="Sent curriculum review case studies to Catherine.",
                    outcome="Shared with academic board"),
            Contact(client_id=clients[1].id, date=date(2025, 9, 18),
                    time=time(11, 0),
                    contact_type="phone",
                    notes="Finally reached technical director — positive on assessment.",
                    outcome="Board meeting scheduled for October to discuss"),
            Contact(client_id=clients[11].id, date=date(2025, 9, 22),
                    time=time(15, 0),
                    contact_type="phone",
                    notes="Follow-up call with Priya — reviewed our introductory pack.",
                    outcome="Wants to discuss compliance consulting in detail"),
            Contact(client_id=clients[13].id, date=date(2025, 9, 25),
                    contact_type="email",
                    notes="Second outreach to Stonewick Retail about inventory systems.",
                    outcome="Daniel replied — has budget for Q1 2026 project"),

            # ── October 2025 — face-to-face meetings, deepening relationships ──
            Contact(client_id=clients[0].id, date=date(2025, 10, 3),
                    time=time(11, 0),
                    contact_type="meeting",
                    notes="First face-to-face meeting at their Birmingham office.",
                    outcome="Strong interest — requested formal proposal"),
            Contact(client_id=clients[1].id, date=date(2025, 10, 10),
                    time=time(14, 0),
                    contact_type="meeting",
                    notes="Board presentation on production line upgrade proposal.",
                    outcome="Board approved budget — technical director to lead"),
            Contact(client_id=clients[1].id, date=date(2025, 10, 18),
                    contact_type="email",
                    notes="Sent detailed proposal for production line assessment.",
                    outcome="Forwarded to technical director for sign-off"),
            Contact(client_id=clients[6].id, date=date(2025, 10, 8),
                    time=time(12, 0),
                    contact_type="meeting",
                    notes="Meeting with Helen at Fenwick & Cole Bristol office.",
                    outcome="Interested in cloud accounting migration — needs partner approval"),
            Contact(client_id=clients[5].id, date=date(2025, 10, 15),
                    time=time(10, 0),
                    contact_type="phone",
                    notes="Richard back from holiday — discussed commercial units.",
                    outcome="Wants to view two units in person"),
            Contact(client_id=clients[9].id, date=date(2025, 10, 20),
                    contact_type="email",
                    notes="Sent brand refresh proposal and pricing to Lucy.",
                    outcome="Budget approved — wants to start in January"),
            Contact(client_id=clients[3].id, date=date(2025, 10, 24),
                    time=time(15, 30),
                    contact_type="phone",
                    notes="James called back — board interested in logistics audit.",
                    outcome="Wants to schedule site visit in November"),
            Contact(client_id=clients[7].id, date=date(2025, 10, 28),
                    time=time(9, 0),
                    contact_type="phone",
                    notes="Post-harvest call with Tom about supply chain.",
                    outcome="Ready to discuss seasonal contract terms"),

            # ── November 2025 — proposals and negotiations ──
            Contact(client_id=clients[0].id, date=date(2025, 11, 4),
                    contact_type="email",
                    notes="Sent formal consultancy proposal to Margaret.",
                    outcome="Under review — meeting scheduled for December"),
            Contact(client_id=clients[8].id, date=date(2025, 11, 7),
                    time=time(9, 30),
                    contact_type="meeting",
                    notes="On-site visit to review current engineering workflows.",
                    outcome="Identified three areas for improvement"),
            Contact(client_id=clients[3].id, date=date(2025, 11, 12),
                    time=time(10, 0),
                    contact_type="meeting",
                    notes="Logistics site visit at Pemberton depot in Leeds.",
                    outcome="Major inefficiencies found in routing — strong case for engagement"),
            Contact(client_id=clients[10].id, date=date(2025, 11, 17),
                    time=time(14, 0),
                    contact_type="meeting",
                    notes="Coffee meeting with William at a Canary Wharf cafe.",
                    outcome="Agreed to a January strategy workshop"),
            Contact(client_id=clients[10].id, date=date(2025, 11, 20),
                    contact_type="email",
                    notes="Referral from industry contact — sent introductory pack.",
                    outcome="William replied, keen to discuss in new year"),
            Contact(client_id=clients[7].id, date=date(2025, 11, 21),
                    contact_type="email",
                    notes="Sent draft seasonal supply contract to Tom.",
                    outcome="Reviewing with his farm manager"),
            Contact(client_id=clients[11].id, date=date(2025, 11, 25),
                    time=time(11, 0),
                    contact_type="meeting",
                    notes="Met Priya at healthcare industry conference in Manchester.",
                    outcome="Detailed discussion — wants formal compliance proposal"),
            Contact(client_id=clients[13].id, date=date(2025, 11, 28),
                    time=time(16, 0),
                    contact_type="phone",
                    notes="Call with Daniel about Q1 inventory project timeline.",
                    outcome="Confirmed January kick-off if proposal approved"),

            # ── December 2025 — year-end wrap-up, holiday period ──
            Contact(client_id=clients[0].id, date=date(2025, 12, 1),
                    time=time(14, 0),
                    contact_type="meeting",
                    notes="Review meeting with Margaret — went through proposal detail.",
                    outcome="Verbal agreement — formal sign-off in January"),
            Contact(client_id=clients[14].id, date=date(2025, 12, 2),
                    contact_type="email",
                    notes="Sent energy audit proposal document.",
                    outcome="Under internal review"),
            Contact(client_id=clients[1].id, date=date(2025, 12, 5),
                    contact_type="email",
                    notes="Sent contract for production line assessment engagement.",
                    outcome="David signed — project starts February"),
            Contact(client_id=clients[6].id, date=date(2025, 12, 8),
                    time=time(10, 0),
                    contact_type="phone",
                    notes="Partner approval for accounting migration — Helen confirmed.",
                    outcome="Starting scoping work in March"),
            Contact(client_id=clients[11].id, date=date(2025, 12, 15),
                    time=time(10, 0),
                    contact_type="phone",
                    notes="Initial call with Priya about healthcare compliance consulting.",
                    outcome="Scheduled January meeting"),
            Contact(client_id=clients[8].id, date=date(2025, 12, 10),
                    contact_type="email",
                    notes="Sent improvement recommendations report to Alan.",
                    outcome="Alan grateful — wants to discuss implementation in new year"),
            Contact(client_id=clients[4].id, date=date(2025, 12, 12),
                    time=time(11, 0),
                    contact_type="phone",
                    notes="Year-end check-in with Emily about catering partnership.",
                    outcome="Still under review — events director on leave until January"),
            Contact(client_id=clients[5].id, date=date(2025, 12, 18),
                    contact_type="email",
                    notes="Sent updated property valuations for two commercial units.",
                    outcome="Richard reviewing over Christmas"),
            Contact(client_id=clients[12].id, date=date(2025, 12, 19),
                    time=time(15, 0),
                    contact_type="phone",
                    notes="Quick call with Catherine — academic board approved exploration.",
                    outcome="Formal meeting planned for February"),

            # ── January 2026 — new year, active engagement ──
            Contact(client_id=clients[0].id, date=date(2026, 1, 6),
                    contact_type="email",
                    notes="Sent contract for legal consultancy support engagement.",
                    outcome="Margaret signed — project kicks off February"),
            Contact(client_id=clients[10].id, date=date(2026, 1, 8),
                    time=time(14, 0),
                    contact_type="meeting",
                    notes="Strategy workshop at Oakbridge offices in Canary Wharf.",
                    outcome="Agreed on scope for pilot project"),
            Contact(client_id=clients[9].id, date=date(2026, 1, 13),
                    time=time(10, 0),
                    contact_type="meeting",
                    notes="Brand refresh kick-off meeting at Whitmore studio.",
                    outcome="Defined brand guidelines, colour palette, and timeline"),
            Contact(client_id=clients[11].id, date=date(2026, 1, 22),
                    time=time(11, 30),
                    contact_type="meeting",
                    notes="Presented compliance audit framework to leadership team.",
                    outcome="Requested pricing for full audit"),
            Contact(client_id=clients[7].id, date=date(2026, 1, 15),
                    time=time(9, 0),
                    contact_type="phone",
                    notes="Contract terms discussion with Tom and his farm manager.",
                    outcome="Minor amendments requested — near final"),
            Contact(client_id=clients[13].id, date=date(2026, 1, 20),
                    time=time(15, 0),
                    contact_type="phone",
                    notes="Daniel confirmed Q1 budget allocation for inventory project.",
                    outcome="Wants detailed implementation plan by February"),
            Contact(client_id=clients[12].id, date=date(2026, 1, 28),
                    contact_type="email",
                    notes="Responded to inbound enquiry about education sector consulting.",
                    outcome="Sent case studies from similar projects"),
            Contact(client_id=clients[3].id, date=date(2026, 1, 30),
                    contact_type="email",
                    notes="Sent logistics audit engagement terms to James.",
                    outcome="Under review by operations director"),

            # ── February 2026 — deep engagement, demos, negotiations ──
            Contact(client_id=clients[0].id, date=date(2026, 2, 3),
                    time=time(10, 0),
                    contact_type="meeting",
                    notes="Project kick-off meeting with Margaret and her team.",
                    outcome="Workstream leads assigned, weekly check-ins agreed"),
            Contact(client_id=clients[1].id, date=date(2026, 2, 5),
                    time=time(9, 0),
                    contact_type="meeting",
                    notes="Production line assessment kick-off at Brightwell Works.",
                    outcome="Baseline measurements taken, two-week data collection started"),
            Contact(client_id=clients[13].id, date=date(2026, 2, 5),
                    time=time(15, 0),
                    contact_type="phone",
                    notes="Exploratory call about retail inventory optimisation.",
                    outcome="Interested — wants to see ROI projections"),
            Contact(client_id=clients[12].id, date=date(2026, 2, 14),
                    time=time(10, 0),
                    contact_type="meeting",
                    notes="Campus tour and requirements gathering session.",
                    outcome="Detailed brief received, preparing proposal"),
            Contact(client_id=clients[9].id, date=date(2026, 2, 10),
                    contact_type="email",
                    notes="Shared first round of brand concepts with Lucy.",
                    outcome="Very positive — minor tweaks requested"),
            Contact(client_id=clients[4].id, date=date(2026, 2, 12),
                    time=time(14, 0),
                    contact_type="meeting",
                    notes="Meeting with Emily and events director about partnership.",
                    outcome="Agreed terms in principle — contract being drafted"),
            Contact(client_id=clients[4].id, date=date(2026, 2, 20),
                    contact_type="email",
                    notes="Sent revised catering partnership terms after feedback.",
                    outcome="Under review by their events director"),
            Contact(client_id=clients[11].id, date=date(2026, 2, 18),
                    contact_type="email",
                    notes="Sent compliance audit pricing and detailed scope document.",
                    outcome="Priya discussing with finance team"),
            Contact(client_id=clients[7].id, date=date(2026, 2, 24),
                    contact_type="email",
                    notes="Sent final contract with agreed amendments to Tom.",
                    outcome="Signed and returned — supply partnership active"),
            Contact(client_id=clients[14].id, date=date(2026, 2, 26),
                    time=time(11, 0),
                    contact_type="phone",
                    notes="Fiona called — energy audit approved by CEO.",
                    outcome="Starting in April, wants project plan"),

            # ── March 2026 — current month, high activity ──
            Contact(client_id=clients[0].id, date=date(2026, 3, 2),
                    time=time(10, 30),
                    contact_type="phone",
                    notes="Weekly check-in with Margaret — project on track.",
                    outcome="First deliverable due next week"),
            Contact(client_id=clients[13].id, date=date(2026, 3, 1),
                    contact_type="email",
                    notes="Sent ROI projections and implementation timeline.",
                    outcome="Shared with board, decision expected April"),
            Contact(client_id=clients[5].id, date=date(2026, 3, 3),
                    time=time(14, 0),
                    contact_type="meeting",
                    notes="Property viewing with Richard — two commercial units.",
                    outcome="Interested in Unit B, wants lease terms"),
            Contact(client_id=clients[5].id, date=date(2026, 3, 5),
                    time=time(9, 0),
                    contact_type="phone",
                    notes="Followed up on property portfolio — discussed specific listings.",
                    outcome="Narrowed interest to three commercial units"),
            Contact(client_id=clients[6].id, date=date(2026, 3, 6),
                    time=time(10, 0),
                    contact_type="meeting",
                    notes="Accounting migration scoping workshop at Fenwick & Cole.",
                    outcome="Defined data migration plan and timeline"),
            Contact(client_id=clients[6].id, date=date(2026, 3, 8),
                    contact_type="email",
                    notes="Sent accounting software integration proposal.",
                    outcome="Helen forwarded to IT department for review"),
            Contact(client_id=clients[1].id, date=date(2026, 3, 9),
                    time=time(11, 0),
                    contact_type="meeting",
                    notes="Mid-project review at Brightwell — data collection complete.",
                    outcome="Preliminary findings positive, full report due March 20"),
            Contact(client_id=clients[9].id, date=date(2026, 3, 7),
                    contact_type="email",
                    notes="Delivered final brand package to Lucy.",
                    outcome="Lucy delighted — wants to discuss website redesign next"),
            Contact(client_id=clients[10].id, date=date(2026, 3, 10),
                    time=time(14, 0),
                    contact_type="meeting",
                    notes="Pilot project progress review with William.",
                    outcome="On track — discussing extension to full engagement"),
            Contact(client_id=clients[3].id, date=date(2026, 3, 11),
                    time=time(16, 0),
                    contact_type="phone",
                    notes="James confirmed logistics audit engagement — signed contract.",
                    outcome="Starting April, site access arranged"),
            Contact(client_id=clients[11].id, date=date(2026, 3, 12),
                    time=time(10, 0),
                    contact_type="phone",
                    notes="Priya confirmed compliance audit budget approved.",
                    outcome="Project start May, preparing team"),

            # ── Recent relative contacts (this week) ──
            Contact(client_id=clients[0].id, date=today - timedelta(days=2),
                    time=time(10, 30),
                    contact_type="phone", notes="Discussed quarterly review requirements.",
                    outcome="Agreed to send proposal by Friday"),
            Contact(client_id=clients[0].id, date=today - timedelta(days=10),
                    time=time(14, 0),
                    contact_type="meeting", notes="Initial consultation at their offices.",
                    outcome="Interested in full service package"),
            Contact(client_id=clients[1].id, date=today - timedelta(days=1),
                    contact_type="email", notes="Sent revised quotation for production line upgrade.",
                    outcome="Awaiting board approval"),
            Contact(client_id=clients[2].id, date=today,
                    time=time(11, 0),
                    contact_type="meeting", notes="Software demo at their Salford office.",
                    outcome="Very positive — scheduling trial period"),
            Contact(client_id=clients[2].id, date=today - timedelta(days=14),
                    contact_type="email", notes="Sent introductory brochure and case studies.",
                    outcome="Requested a demo"),
            Contact(client_id=clients[7].id, date=today - timedelta(days=4),
                    time=time(13, 45),
                    contact_type="phone", notes="Discussed seasonal supply contract.",
                    outcome="Drafting contract terms"),
        ]
        # Assign ownership to contacts based on their client's owner
        for c in contacts:
            c.user_id = db.session.get(Client, c.client_id).user_id
        db.session.add_all(contacts)

        # --- Follow-ups — full year Apr 2025 – Mar 2026 + future pipeline ---
        followups = [
            # ── April 2025 — early pipeline follow-ups (all completed) ──
            FollowUp(client_id=clients[0].id, due_date=date(2025, 4, 9),
                      priority="medium",
                      notes="Follow up on cold email to Margaret",
                      completed=True),
            FollowUp(client_id=clients[1].id, due_date=date(2025, 4, 14),
                      priority="medium",
                      notes="Chase callback from Brightwell reception",
                      completed=True),
            FollowUp(client_id=clients[5].id, due_date=date(2025, 4, 17),
                      priority="low",
                      notes="Resend property brochure when Richard back from leave",
                      completed=True),
            FollowUp(client_id=clients[3].id, due_date=date(2025, 4, 25),
                      priority="medium",
                      notes="Send logistics case studies to James Pemberton",
                      completed=True),

            # ── May 2025 ──
            FollowUp(client_id=clients[0].id, due_date=date(2025, 5, 8),
                      priority="high",
                      notes="Send detailed consultancy proposal to Margaret",
                      completed=True),
            FollowUp(client_id=clients[1].id, due_date=date(2025, 5, 15),
                      priority="high",
                      notes="Arrange factory site visit with David Brightwell",
                      completed=True),
            FollowUp(client_id=clients[4].id, due_date=date(2025, 5, 22),
                      priority="medium",
                      notes="Send catering partnership proposal to Emily",
                      completed=True),
            FollowUp(client_id=clients[14].id, due_date=date(2025, 5, 28),
                      priority="low",
                      notes="Follow up on sustainability consulting email to Fiona",
                      completed=True),

            # ── June 2025 ──
            FollowUp(client_id=clients[0].id, due_date=date(2025, 6, 6),
                      priority="medium",
                      notes="Chase Margaret on proposal review",
                      completed=True),
            FollowUp(client_id=clients[1].id, due_date=date(2025, 6, 16),
                      priority="high",
                      notes="Send production line assessment report after site visit",
                      completed=True),
            FollowUp(client_id=clients[10].id, due_date=date(2025, 6, 20),
                      priority="medium",
                      notes="Schedule introductory call with William Oakbridge",
                      completed=True),
            FollowUp(client_id=clients[8].id, due_date=date(2025, 6, 27),
                      priority="low",
                      notes="Follow up with Alan about September engineering project",
                      completed=True),
            FollowUp(client_id=clients[12].id, due_date=date(2025, 6, 25),
                      priority="low",
                      notes="Send education consulting info to Catherine",
                      completed=True),

            # ── July 2025 ──
            FollowUp(client_id=clients[0].id, due_date=date(2025, 7, 7),
                      priority="medium",
                      notes="Discuss scope questions with Margaret before she leaves",
                      completed=True),
            FollowUp(client_id=clients[3].id, due_date=date(2025, 7, 18),
                      priority="medium",
                      notes="Send logistics audit pricing to James",
                      completed=True),
            FollowUp(client_id=clients[14].id, due_date=date(2025, 7, 30),
                      priority="medium",
                      notes="Call Fiona about energy audit proposal",
                      completed=True),
            FollowUp(client_id=clients[12].id, due_date=date(2025, 7, 22),
                      priority="low",
                      notes="Follow up with Catherine about curriculum review",
                      completed=True),

            # ── August 2025 ──
            FollowUp(client_id=clients[1].id, due_date=date(2025, 8, 8),
                      priority="medium",
                      notes="Chase technical director on assessment report",
                      completed=True),
            FollowUp(client_id=clients[5].id, due_date=date(2025, 8, 14),
                      priority="low",
                      notes="Send property portfolio to Richard",
                      completed=True),
            FollowUp(client_id=clients[8].id, due_date=date(2025, 8, 20),
                      priority="medium",
                      notes="Arrange site visit with Alan before September project",
                      completed=True),
            FollowUp(client_id=clients[9].id, due_date=date(2025, 8, 28),
                      priority="low",
                      notes="Reconnect with Lucy about branding project",
                      completed=True),

            # ── September 2025 ──
            FollowUp(client_id=clients[14].id, due_date=date(2025, 9, 5),
                      priority="high",
                      notes="Send formal energy audit proposal to Fiona",
                      completed=True),
            FollowUp(client_id=clients[9].id, due_date=date(2025, 9, 8),
                      priority="high",
                      notes="Creative brief meeting with Lucy at Whitmore studio",
                      completed=True),
            FollowUp(client_id=clients[8].id, due_date=date(2025, 9, 10),
                      priority="high",
                      notes="Complete site visit at Mercer Engineering",
                      completed=True),
            FollowUp(client_id=clients[1].id, due_date=date(2025, 9, 22),
                      priority="medium",
                      notes="Follow up with technical director on assessment",
                      completed=True),
            FollowUp(client_id=clients[11].id, due_date=date(2025, 9, 25),
                      priority="medium",
                      notes="Call Priya about compliance consulting interest",
                      completed=True),
            FollowUp(client_id=clients[13].id, due_date=date(2025, 9, 29),
                      priority="low",
                      notes="Follow up second outreach to Daniel at Stonewick",
                      completed=True),

            # ── October 2025 ──
            FollowUp(client_id=clients[0].id, due_date=date(2025, 10, 1),
                      priority="high",
                      notes="Prepare for face-to-face meeting with Margaret",
                      completed=True),
            FollowUp(client_id=clients[0].id, due_date=date(2025, 10, 10),
                      priority="high",
                      notes="Prepare formal proposal after initial meeting",
                      completed=True),
            FollowUp(client_id=clients[1].id, due_date=date(2025, 10, 15),
                      priority="high",
                      notes="Prepare board presentation for Brightwell",
                      completed=True),
            FollowUp(client_id=clients[6].id, due_date=date(2025, 10, 10),
                      priority="medium",
                      notes="Schedule meeting with Helen at Fenwick & Cole",
                      completed=True),
            FollowUp(client_id=clients[5].id, due_date=date(2025, 10, 18),
                      priority="low",
                      notes="Follow up with Richard on commercial units",
                      completed=True),
            FollowUp(client_id=clients[9].id, due_date=date(2025, 10, 22),
                      priority="medium",
                      notes="Send brand refresh proposal and pricing to Lucy",
                      completed=True),
            FollowUp(client_id=clients[7].id, due_date=date(2025, 10, 30),
                      priority="medium",
                      notes="Call Tom about supply chain contract terms",
                      completed=True),

            # ── November 2025 ──
            FollowUp(client_id=clients[0].id, due_date=date(2025, 11, 6),
                      priority="high",
                      notes="Send formal consultancy proposal to Margaret",
                      completed=True),
            FollowUp(client_id=clients[1].id, due_date=date(2025, 11, 1),
                      priority="medium",
                      notes="Chase technical director on proposal feedback",
                      completed=True),
            FollowUp(client_id=clients[8].id, due_date=date(2025, 11, 15),
                      priority="high",
                      notes="Send improvement recommendations after site visit",
                      completed=True),
            FollowUp(client_id=clients[3].id, due_date=date(2025, 11, 14),
                      priority="high",
                      notes="Arrange logistics site visit at Pemberton depot",
                      completed=True),
            FollowUp(client_id=clients[10].id, due_date=date(2025, 11, 19),
                      priority="medium",
                      notes="Coffee meeting with William Oakbridge",
                      completed=True),
            FollowUp(client_id=clients[11].id, due_date=date(2025, 11, 27),
                      priority="medium",
                      notes="Prepare formal compliance proposal for Priya",
                      completed=True),
            FollowUp(client_id=clients[13].id, due_date=date(2025, 11, 30),
                      priority="low",
                      notes="Call Daniel about Q1 inventory project timeline",
                      completed=True),

            # ── December 2025 ──
            FollowUp(client_id=clients[0].id, due_date=date(2025, 12, 3),
                      priority="high",
                      notes="Review meeting with Margaret — go through proposal detail",
                      completed=True),
            FollowUp(client_id=clients[1].id, due_date=date(2025, 12, 8),
                      priority="medium",
                      notes="Send contract for production line assessment",
                      completed=True),
            FollowUp(client_id=clients[6].id, due_date=date(2025, 12, 10),
                      priority="medium",
                      notes="Chase Helen on partner approval for accounting migration",
                      completed=True),
            FollowUp(client_id=clients[8].id, due_date=date(2025, 12, 12),
                      priority="medium",
                      notes="Send improvement recommendations report to Alan",
                      completed=True),
            FollowUp(client_id=clients[12].id, due_date=date(2025, 12, 22),
                      priority="low",
                      notes="Quick call with Catherine before Christmas",
                      completed=True),
            FollowUp(client_id=clients[4].id, due_date=date(2025, 12, 15),
                      priority="low",
                      notes="Year-end check-in with Emily on catering partnership",
                      completed=True),

            # ── January 2026 ──
            FollowUp(client_id=clients[0].id, due_date=date(2026, 1, 7),
                      priority="high",
                      notes="Send contract for legal consultancy engagement",
                      completed=True),
            FollowUp(client_id=clients[10].id, due_date=date(2026, 1, 5),
                      priority="medium",
                      notes="Schedule new year strategy workshop with William",
                      completed=True),
            FollowUp(client_id=clients[9].id, due_date=date(2026, 1, 12),
                      priority="high",
                      notes="Brand refresh kick-off meeting with Lucy",
                      completed=True),
            FollowUp(client_id=clients[11].id, due_date=date(2026, 1, 20),
                      priority="high",
                      notes="Prepare compliance audit presentation for leadership",
                      completed=True),
            FollowUp(client_id=clients[7].id, due_date=date(2026, 1, 16),
                      priority="medium",
                      notes="Finalise seasonal contract amendments with Tom",
                      completed=True),
            FollowUp(client_id=clients[13].id, due_date=date(2026, 1, 22),
                      priority="medium",
                      notes="Send implementation plan to Daniel at Stonewick",
                      completed=True),
            FollowUp(client_id=clients[3].id, due_date=date(2026, 1, 31),
                      priority="medium",
                      notes="Send logistics audit engagement terms to James",
                      completed=True),

            # ── February 2026 ──
            FollowUp(client_id=clients[0].id, due_date=date(2026, 2, 2),
                      priority="high",
                      notes="Prepare project kick-off materials for Margaret",
                      completed=True),
            FollowUp(client_id=clients[1].id, due_date=date(2026, 2, 4),
                      priority="high",
                      notes="Prepare assessment kick-off at Brightwell Works",
                      completed=True),
            FollowUp(client_id=clients[14].id, due_date=date(2026, 2, 1),
                      priority="low",
                      notes="Follow up on energy audit proposal status",
                      completed=True),
            FollowUp(client_id=clients[9].id, due_date=date(2026, 2, 12),
                      priority="medium",
                      notes="Share first round brand concepts with Lucy",
                      completed=True),
            FollowUp(client_id=clients[4].id, due_date=date(2026, 2, 14),
                      priority="medium",
                      notes="Meeting with Emily and events director",
                      completed=True),
            FollowUp(client_id=clients[11].id, due_date=date(2026, 2, 20),
                      priority="medium",
                      notes="Send compliance audit pricing and scope document",
                      completed=True),
            FollowUp(client_id=clients[7].id, due_date=date(2026, 2, 25),
                      priority="low",
                      notes="Send final contract to Tom — supply partnership",
                      completed=True),
            FollowUp(client_id=clients[14].id, due_date=date(2026, 2, 28),
                      priority="medium",
                      notes="Discuss energy audit project plan with Fiona",
                      completed=True),

            # ── March 2026 — current month mix of completed + pending ──
            FollowUp(client_id=clients[0].id, due_date=today - timedelta(days=5),
                      priority="high", notes="Prepare meeting summary notes",
                      completed=True),
            FollowUp(client_id=clients[2].id, due_date=today - timedelta(days=2),
                      priority="medium", notes="Send demo recording link",
                      completed=True),
            FollowUp(client_id=clients[8].id, due_date=today - timedelta(days=7),
                      priority="low", notes="Check if reactivation is possible",
                      completed=True),
            FollowUp(client_id=clients[6].id, due_date=date(2026, 3, 4),
                      priority="high",
                      notes="Prepare scoping workshop materials for Fenwick & Cole",
                      completed=True),
            FollowUp(client_id=clients[9].id, due_date=date(2026, 3, 6),
                      priority="high",
                      notes="Deliver final brand package to Lucy",
                      completed=True),
            FollowUp(client_id=clients[1].id, due_date=date(2026, 3, 8),
                      priority="high",
                      notes="Prepare mid-project review presentation for Brightwell",
                      completed=True),

            # Current and upcoming
            FollowUp(client_id=clients[0].id, due_date=today,
                      due_time=time(9, 0),
                      priority="high", notes="Send quarterly review proposal"),
            FollowUp(client_id=clients[1].id, due_date=today,
                      due_time=time(14, 30),
                      priority="medium", notes="Chase board decision on quotation"),
            FollowUp(client_id=clients[2].id, due_date=today + timedelta(days=2),
                      due_time=time(10, 0),
                      priority="high", notes="Set up trial period access"),
            FollowUp(client_id=clients[3].id, due_date=today + timedelta(days=1),
                      priority="medium", notes="Send detailed logistics brochure"),
            FollowUp(client_id=clients[4].id, due_date=today + timedelta(days=3),
                      due_time=time(11, 30),
                      priority="low", notes="Prepare for scheduled call"),
            FollowUp(client_id=clients[5].id, due_date=today - timedelta(days=1),
                      due_time=time(9, 0),
                      priority="high", notes="Send property portfolio — promised yesterday"),
            FollowUp(client_id=clients[6].id, due_date=today - timedelta(days=3),
                      priority="medium", notes="Follow up from conference meeting"),
            FollowUp(client_id=clients[7].id, due_date=today + timedelta(days=5),
                      priority="low", notes="Finalise seasonal contract terms"),
            FollowUp(client_id=clients[9].id, due_date=today + timedelta(days=7),
                      due_time=time(16, 0),
                      priority="medium", notes="Follow up on budget confirmation"),

            # ── Q2 2026 (Apr–Jun) — near-term pipeline ──
            FollowUp(client_id=clients[14].id, due_date=date(2026, 4, 1),
                      due_time=time(9, 0),
                      priority="high",
                      notes="Energy audit project kick-off with Fiona"),
            FollowUp(client_id=clients[3].id, due_date=date(2026, 4, 6),
                      due_time=time(10, 0),
                      priority="high",
                      notes="Logistics audit kick-off at Pemberton depot"),
            FollowUp(client_id=clients[10].id, due_date=date(2026, 4, 7),
                      due_time=time(10, 0),
                      priority="high",
                      notes="Kick-off meeting for pilot consulting project"),
            FollowUp(client_id=clients[13].id, due_date=date(2026, 4, 15),
                      priority="high",
                      notes="Chase board decision on retail optimisation proposal"),
            FollowUp(client_id=clients[0].id, due_date=date(2026, 4, 20),
                      priority="medium",
                      notes="First deliverable review with Margaret"),
            FollowUp(client_id=clients[11].id, due_date=date(2026, 5, 1),
                      due_time=time(14, 0),
                      priority="medium",
                      notes="Compliance audit project kick-off with Priya"),
            FollowUp(client_id=clients[12].id, due_date=date(2026, 5, 20),
                      priority="medium",
                      notes="Submit education consulting proposal"),
            FollowUp(client_id=clients[9].id, due_date=date(2026, 5, 15),
                      priority="medium",
                      notes="Website redesign scoping with Lucy"),
            FollowUp(client_id=clients[1].id, due_date=date(2026, 6, 1),
                      priority="medium",
                      notes="Final assessment report delivery to Brightwell"),
            FollowUp(client_id=clients[4].id, due_date=date(2026, 6, 10),
                      priority="low",
                      notes="Follow up on catering partnership terms review"),
            FollowUp(client_id=clients[6].id, due_date=date(2026, 6, 15),
                      priority="medium",
                      notes="Accounting migration phase one completion review"),

            # ── Q3 2026 (Jul–Sep) — mid-term planning ──
            FollowUp(client_id=clients[0].id, due_date=date(2026, 7, 1),
                      priority="medium",
                      notes="Schedule mid-year service review with Margaret"),
            FollowUp(client_id=clients[7].id, due_date=date(2026, 8, 15),
                      priority="medium",
                      notes="Renegotiate autumn supply contract terms"),
            FollowUp(client_id=clients[1].id, due_date=date(2026, 9, 1),
                      priority="low",
                      notes="Check in on production line upgrade progress"),
            FollowUp(client_id=clients[14].id, due_date=date(2026, 9, 20),
                      priority="low",
                      notes="Re-engage about energy audit — new financial year"),

            # ── Q4 2026 (Oct–Dec) — long-term reminders ──
            FollowUp(client_id=clients[10].id, due_date=date(2026, 10, 5),
                      priority="low",
                      notes="Review pilot project outcomes and plan phase two"),
            FollowUp(client_id=clients[2].id, due_date=date(2026, 11, 1),
                      priority="low",
                      notes="Annual contract renewal discussion with Sarah"),
            FollowUp(client_id=clients[3].id, due_date=date(2026, 12, 1),
                      priority="low",
                      notes="Year-end review — assess logistics partnership value"),
        ]
        # Assign ownership to follow-ups based on their client's owner
        for fu in followups:
            fu.user_id = db.session.get(Client, fu.client_id).user_id
        db.session.add_all(followups)

        # --- Custom Field Values (sample data for some clients) ---
        addr_def = custom_field_defs[0]     # Address
        linkedin_def = custom_field_defs[1]  # LinkedIn
        twitter_def = custom_field_defs[2]   # Twitter / X

        custom_values = [
            # Existing values
            CustomFieldValue(definition_id=addr_def.id, client_id=clients[0].id,
                             value="14 Temple Row, Birmingham B2 5JR"),
            CustomFieldValue(definition_id=addr_def.id, client_id=clients[2].id,
                             value="Unit 7, MediaCity, Salford M50 2HE"),
            CustomFieldValue(definition_id=linkedin_def.id, client_id=clients[2].id,
                             value="https://linkedin.com/company/hargreaves-digital"),
            # New values
            CustomFieldValue(definition_id=addr_def.id, client_id=clients[1].id,
                             value="Brightwell Works, Aston Road, Birmingham B6 4RJ"),
            CustomFieldValue(definition_id=addr_def.id, client_id=clients[10].id,
                             value="3rd Floor, 25 Canada Square, London E14 5LQ"),
            CustomFieldValue(definition_id=addr_def.id, client_id=clients[11].id,
                             value="Redcastle House, Princess Street, Manchester M1 4HB"),
            CustomFieldValue(definition_id=linkedin_def.id, client_id=clients[10].id,
                             value="https://linkedin.com/company/oakbridge-consulting"),
            CustomFieldValue(definition_id=linkedin_def.id, client_id=clients[0].id,
                             value="https://linkedin.com/company/thornbury-associates"),
            CustomFieldValue(definition_id=twitter_def.id, client_id=clients[9].id,
                             value="https://x.com/whitmorecreative"),
            CustomFieldValue(definition_id=twitter_def.id, client_id=clients[2].id,
                             value="https://x.com/hargreavesdigital"),
            CustomFieldValue(definition_id=twitter_def.id, client_id=clients[11].id,
                             value="https://x.com/redcastlehealth"),
        ]
        db.session.add_all(custom_values)

        db.session.commit()
        print(
            f"Seeded {len(users)} users, {len(clients)} clients, {len(contacts)} contacts, "
            f"{len(followups)} follow-ups, {len(custom_values)} custom field values, "
            f"{len(attachment_cats)} attachment categories, {len(attachment_tags)} attachment tags."
        )


if __name__ == "__main__":
    seed()
